"""Generate a plain-text-friendly technical function inventory."""

from __future__ import annotations

import ast
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "docs" / "technical" / "function_inventory.md"


FUNCTIONS: list[dict[str, Any]] = [
    {
        "area": "Stage 0 - Environment",
        "file": "src/tennis_vision/environment.py",
        "function": "run_environment_checks",
        "purpose": "Runs the complete local environment check for Python, folders, imports, and ffmpeg.",
        "inputs": ["project root path"],
        "outputs": ["environment status dictionary"],
        "called_by": ["scripts/doctor.py"],
        "why": "This tells the Product Owner whether local development can continue before video analysis stages run.",
        "notes": "ffmpeg missing is recorded as warning unless a later stage needs it.",
    },
    {
        "area": "Stage 0 - Environment",
        "file": "src/tennis_vision/environment.py",
        "function": "check_required_packages",
        "purpose": "Checks whether required Python packages can be imported.",
        "inputs": ["package name list"],
        "outputs": ["package import status"],
        "called_by": ["run_environment_checks"],
        "why": "Missing packages are common setup friction and should be visible immediately.",
    },
    {
        "area": "Stage 0 - Environment",
        "file": "src/tennis_vision/environment.py",
        "function": "check_ffmpeg",
        "purpose": "Checks whether ffmpeg is available from the shell.",
        "inputs": ["none"],
        "outputs": ["ffmpeg availability and path/status"],
        "called_by": ["run_environment_checks"],
        "why": "Video work may eventually need ffmpeg, but Stage 1 proved MOV reading can work through OpenCV.",
    },
    {
        "area": "Reports",
        "file": "src/tennis_vision/report.py",
        "function": "write_json_report",
        "purpose": "Writes a machine-readable JSON report.",
        "inputs": ["report path", "report dictionary"],
        "outputs": ["JSON report file"],
        "called_by": ["stage scripts"],
        "why": "Reports are the durable evidence layer for every experiment.",
    },
    {
        "area": "Reports",
        "file": "src/tennis_vision/report.py",
        "function": "write_markdown_report",
        "purpose": "Writes a human-readable Markdown report.",
        "inputs": ["report path", "title", "sections"],
        "outputs": ["Markdown report file"],
        "called_by": ["stage scripts"],
        "why": "The Product Owner can inspect results without parsing JSON.",
    },
    {
        "area": "Friction",
        "file": "src/tennis_vision/friction.py",
        "function": "friction_band",
        "purpose": "Converts a numeric friction score into low, medium, high, or blocking.",
        "inputs": ["score from 0 to 100"],
        "outputs": ["friction band text"],
        "called_by": ["all friction scoring helpers"],
        "why": "Keeps operational risk readable across stages.",
    },
    {
        "area": "Friction",
        "file": "src/tennis_vision/friction_semantics.py",
        "function": "build_friction_breakdown",
        "purpose": "Builds a multi-dimensional friction breakdown for stage reports.",
        "inputs": ["execution, semantic/model, human-loop, product validation, and downstream correction scores/reasons"],
        "outputs": ["friction_breakdown dictionary"],
        "called_by": ["future ML/CV stage scripts", "scripts/run_stage_8_4_bounce_candidate_propagation.py"],
        "why": "Prevents successful script execution from being mistaken for successful product or model validation.",
    },
    {
        "area": "Friction",
        "file": "src/tennis_vision/friction_semantics.py",
        "function": "summarize_friction_breakdown",
        "purpose": "Summarizes multi-dimensional friction in one plain-language sentence.",
        "inputs": ["friction_breakdown dictionary"],
        "outputs": ["summary string"],
        "called_by": ["stage scripts"],
        "why": "Makes semantic/product friction visible in reports and console summaries.",
    },
    {
        "area": "Friction",
        "file": "src/tennis_vision/friction_semantics.py",
        "function": "classify_product_validation_status",
        "purpose": "Normalizes product validation status labels.",
        "inputs": ["status text"],
        "outputs": ["normalized status"],
        "called_by": ["build_friction_breakdown"],
        "why": "Visual/model outputs need explicit Product Owner validation status.",
    },
    {
        "area": "Friction",
        "file": "src/tennis_vision/friction_semantics.py",
        "function": "classify_human_loop_level",
        "purpose": "Classifies human-loop friction from manual labeling and review requirements.",
        "inputs": ["manual labels required flag", "manual review required flag", "new manual stage required flag"],
        "outputs": ["human-loop friction dimension"],
        "called_by": ["scripts/run_stage_8_4_bounce_candidate_propagation.py"],
        "why": "Manual review burden should be visible even when a script runs cleanly.",
    },
    *[
        {
            "area": "Friction",
            "file": "src/tennis_vision/friction.py",
            "function": name,
            "purpose": f"Calculates friction for {label}.",
            "inputs": ["stage-specific warning/error/input flags"],
            "outputs": ["friction score dictionary"],
            "called_by": [script],
            "why": "Prevents failures and uncertainty from being hidden.",
        }
        for name, label, script in [
            ("calculate_stage_1_friction_score", "Stage 1 video loading", "scripts/run_stage_1_video_probe.py"),
            ("calculate_stage_2_friction_score", "Stage 2 YOLO CPU inference", "scripts/run_stage_2_yolo_cpu_baseline.py"),
            ("calculate_stage_3_friction_score", "Stage 3 court calibration", "scripts/run_stage_3_court_calibration_probe.py"),
            ("calculate_stage_4_friction_score", "Stage 4 ball candidate probing", "scripts/run_stage_4_ball_tracking_probe.py"),
            ("calculate_stage_5_friction_score", "Stage 5 candidate filtering", "scripts/run_stage_5_ball_candidate_filtering.py"),
            ("calculate_stage_6_friction_score", "Stage 6 trajectory smoothing", "scripts/run_stage_6_trajectory_smoothing.py"),
            ("calculate_stage_7_friction_score", "Stage 7 player interaction", "scripts/run_stage_7_player_interaction_probe.py"),
            ("calculate_stage_8_friction_score", "Stage 8 event timeline", "scripts/run_stage_8_event_timeline.py"),
            ("calculate_stage_8_1_friction_score", "Stage 8.1 timeline validation", "scripts/run_stage_8_1_expand_labels.py"),
            ("calculate_stage_8_2_friction_score", "Stage 8.2 manual event labeling", "scripts/run_stage_8_2_event_labeling_helper.py"),
            ("calculate_stage_8_3_friction_score", "Stage 8.3 event validation", "scripts/run_stage_8_3_event_validation.py"),
            ("calculate_stage_8_4_friction_score", "Stage 8.4 bounce candidate propagation", "scripts/run_stage_8_4_bounce_candidate_propagation.py"),
            ("calculate_stage_9_friction_score", "Stage 9 tactical metrics", "scripts/run_stage_9_tactical_metrics.py"),
            ("calculate_stage_9_1_friction_score", "Stage 9.1 projection coverage", "scripts/run_stage_9_1_projection_coverage.py"),
            ("calculate_stage_10_friction_score", "Stage 10 analytical reporting", "scripts/run_stage_10_analytical_report.py"),
            ("calculate_stage_11_friction_score", "Stage 11 report packaging", "scripts/run_stage_11_report_package.py"),
            ("calculate_stage_12_friction_score", "Stage 12 replay schema generation", "scripts/run_stage_12_replay_schema.py"),
            ("calculate_stage_13_friction_score", "Stage 13 2D tactical replay rendering", "scripts/run_stage_13_2d_tactical_replay.py"),
            ("calculate_stage_14_friction_score", "Stage 14 side-view replay rendering", "scripts/run_stage_14_side_view_replay.py"),
            ("calculate_stage_14_1_friction_score", "Stage 14.1 side-view semantics patch", "scripts/run_stage_14_side_view_replay.py"),
            ("calculate_stage_14_2_friction_score", "Stage 14.2 side-view event disambiguation", "scripts/run_stage_14_side_view_replay.py"),
            ("calculate_stage_14_3_friction_score", "Stage 14.3 validated-event side-view rendering", "scripts/run_stage_14_side_view_replay.py"),
        ]
    ],
    {
        "area": "Stage 1 - Video IO",
        "file": "src/tennis_vision/video_io.py",
        "function": "read_video_metadata",
        "purpose": "Reads file size, frame count, FPS, duration, resolution, and codec metadata.",
        "inputs": ["video path"],
        "outputs": ["metadata dictionary"],
        "called_by": ["scripts/run_stage_1_video_probe.py"],
        "why": "Confirms that the local sample video is readable before later analysis stages.",
    },
    {
        "area": "Stage 1 - Video IO",
        "file": "src/tennis_vision/frame_sampler.py",
        "function": "extract_frames",
        "purpose": "Extracts JPG frames from a video at a fixed interval.",
        "inputs": ["video path", "output folder", "interval", "max frames"],
        "outputs": ["saved frames and extraction statistics"],
        "called_by": ["scripts/run_stage_1_video_probe.py"],
        "why": "Frame extraction is the first concrete video-processing capability.",
    },
    {
        "area": "Stage 2 - YOLO CPU",
        "file": "src/tennis_vision/yolo_cpu.py",
        "function": "load_yolo_model",
        "purpose": "Loads a small YOLO model for local CPU inference.",
        "inputs": ["model name"],
        "outputs": ["YOLO model or load error"],
        "called_by": ["scripts/run_stage_2_yolo_cpu_baseline.py"],
        "why": "Validates whether object detection can run locally without cloud or GPU assumptions.",
    },
    {
        "area": "Stage 2 - YOLO CPU",
        "file": "src/tennis_vision/yolo_cpu.py",
        "function": "run_yolo_cpu_baseline",
        "purpose": "Runs limited YOLO CPU inference and saves annotated frames.",
        "inputs": ["video", "model", "interval", "max frames", "resize width", "confidence"],
        "outputs": ["annotated images and detection summary"],
        "called_by": ["scripts/run_stage_2_yolo_cpu_baseline.py"],
        "why": "Proves the local object detection pipeline is technically possible.",
    },
    {
        "area": "Stage 3 - Court Calibration",
        "file": "src/tennis_vision/court_calibration.py",
        "function": "validate_corner_geometry",
        "purpose": "Checks point order and crossed court polygon geometry.",
        "inputs": ["manual court corner points"],
        "outputs": ["geometry validation status"],
        "called_by": ["validate_points"],
        "why": "Prevents inverted court points from creating a false homography.",
    },
    {
        "area": "Stage 3 - Court Calibration",
        "file": "src/tennis_vision/court_calibration.py",
        "function": "compute_homography",
        "purpose": "Computes the image-to-normalized-court homography from valid corner points.",
        "inputs": ["validated court points"],
        "outputs": ["homography matrix/status"],
        "called_by": ["run_court_calibration_probe"],
        "why": "This is the bridge from video pixels to court-space reasoning.",
    },
    {
        "area": "Stage 3.1 - Court Point Selection",
        "file": "src/tennis_vision/court_point_selector.py",
        "function": "generate_coordinate_grid",
        "purpose": "Draws coordinate grid labels on the calibration reference frame.",
        "inputs": ["reference image", "grid step"],
        "outputs": ["grid image"],
        "called_by": ["scripts/run_stage_3_1_court_point_selector.py"],
        "why": "The user can estimate or verify court point coordinates without a frontend.",
    },
    {
        "area": "Stage 4 - Ball Candidate Probe",
        "file": "src/tennis_vision/ball_tracking_probe.py",
        "function": "detect_ball_candidates",
        "purpose": "Finds yellow/green blob candidates using OpenCV heuristics.",
        "inputs": ["frame", "frame index"],
        "outputs": ["candidate list"],
        "called_by": ["run_ball_tracking_probe"],
        "why": "This showed the first local ball-detection approach produced many false positives.",
    },
    {
        "area": "Stage 4.1 - Manual Ball Labeling",
        "file": "src/tennis_vision/ball_labeling.py",
        "function": "label_frames_interactively",
        "purpose": "Opens OpenCV windows so the user can click the real ball.",
        "inputs": ["video", "frame indices", "output dir", "resize width"],
        "outputs": ["manual labels and overlays"],
        "called_by": ["scripts/run_stage_4_1_ball_labeling_helper.py", "scripts/run_stage_8_1_expand_labels.py"],
        "why": "Manual labels create ground truth when automatic detection is noisy.",
    },
    {
        "area": "Stage 5 - Candidate Filtering and Court Projection",
        "file": "src/tennis_vision/ball_candidate_filtering.py",
        "function": "compare_candidates_to_labels",
        "purpose": "Ranks automatic candidates by distance to manual labels.",
        "inputs": ["candidate rows", "manual labels"],
        "outputs": ["distance rows and summary"],
        "called_by": ["scripts/run_stage_5_ball_candidate_filtering.py"],
        "why": "Quantifies whether automatic candidates are actually near the real ball.",
    },
    {
        "area": "Stage 5 - Candidate Filtering and Court Projection",
        "file": "src/tennis_vision/court_projection.py",
        "function": "project_image_points",
        "purpose": "Projects image-space points into normalized court coordinates.",
        "inputs": ["point rows", "homography matrix"],
        "outputs": ["projected point rows"],
        "called_by": ["Stage 5 and Stage 5.1 scripts"],
        "why": "Court-space projection is required for SwingVision-style spatial analysis.",
    },
    {
        "area": "Stage 5.1 - Candidate Generation Improvement",
        "file": "src/tennis_vision/ball_candidate_improvement.py",
        "function": "generate_hsv_candidates",
        "purpose": "Generates improved HSV color candidates for labeled frames.",
        "inputs": ["frame bundle", "court polygon"],
        "outputs": ["candidate rows"],
        "called_by": ["scripts/run_stage_5_1_candidate_improvement.py"],
        "why": "This strategy dramatically improved ball candidate distance on the sample.",
    },
    {
        "area": "Stage 5.1 - Candidate Generation Improvement",
        "file": "src/tennis_vision/ball_candidate_improvement.py",
        "function": "evaluate_strategies",
        "purpose": "Compares candidate generation strategies against manual labels.",
        "inputs": ["candidates by strategy", "manual labels"],
        "outputs": ["strategy comparison rows and summaries"],
        "called_by": ["scripts/run_stage_5_1_candidate_improvement.py"],
        "why": "Helps decide whether to advance or improve the detector first.",
    },
    {
        "area": "Stage 6 - Trajectory Smoothing",
        "file": "src/tennis_vision/trajectory_smoothing.py",
        "function": "moving_average_smooth",
        "purpose": "Smooths raw and projected ball coordinates with a small moving average.",
        "inputs": ["trajectory rows", "window size"],
        "outputs": ["smoothed trajectory rows"],
        "called_by": ["scripts/run_stage_6_trajectory_smoothing.py"],
        "why": "Creates a first trajectory without hiding sparse or bad detections.",
    },
    {
        "area": "Stage 6 - Trajectory Smoothing",
        "file": "src/tennis_vision/event_segmentation.py",
        "function": "detect_events",
        "purpose": "Creates hypothesis-only event markers from trajectory shape and speed changes.",
        "inputs": ["raw trajectory rows"],
        "outputs": ["event rows and warnings"],
        "called_by": ["scripts/run_stage_6_trajectory_smoothing.py"],
        "why": "Starts event reasoning while preserving uncertainty.",
    },
    {
        "area": "Stage 7 - Player Interaction",
        "file": "src/tennis_vision/player_tracking.py",
        "function": "detect_players",
        "purpose": "Runs local YOLO person detection on selected frames.",
        "inputs": ["video", "frame list", "model", "resize width", "confidence"],
        "outputs": ["player detection rows"],
        "called_by": ["scripts/run_stage_7_player_interaction_probe.py"],
        "why": "Player locations are needed to interpret possible ball-player interactions.",
    },
    {
        "area": "Stage 7 - Player Interaction",
        "file": "src/tennis_vision/ball_player_interaction.py",
        "function": "associate_ball_to_players",
        "purpose": "Associates ball trajectory points with nearby player tracks.",
        "inputs": ["ball rows", "player tracks", "events", "frame tolerance"],
        "outputs": ["distance rows, interaction rows, counts"],
        "called_by": ["scripts/run_stage_7_player_interaction_probe.py"],
        "why": "Turns player proximity into possible-hit hypotheses, not confirmed events.",
    },
    {
        "area": "Stage 7.1 - Player Filtering and Identity",
        "file": "src/tennis_vision/player_filtering.py",
        "function": "score_track_rows",
        "purpose": "Scores person detections using court, size, duration, and confidence signals.",
        "inputs": ["player track rows", "court polygon", "thresholds"],
        "outputs": ["scored rows and track summaries"],
        "called_by": ["scripts/run_stage_7_1_player_filtering.py"],
        "why": "Filters audience and side people so only the main players remain.",
    },
    {
        "area": "Stage 7.1 - Player Filtering and Identity",
        "file": "src/tennis_vision/player_identity.py",
        "function": "build_identity_profiles",
        "purpose": "Builds lightweight clothing-color identity profiles from player crops.",
        "inputs": ["video", "filtered player rows"],
        "outputs": ["identity profile JSON and warnings"],
        "called_by": ["scripts/run_stage_7_1_player_filtering.py"],
        "why": "Player identity should not be permanently tied to near/far side.",
    },
    {
        "area": "Stage 8 - Event Timeline",
        "file": "src/tennis_vision/event_timeline.py",
        "function": "merge_timeline_events",
        "purpose": "Merges nearby trajectory, event, and interaction evidence into timeline clusters.",
        "inputs": ["event rows", "merge window", "FPS"],
        "outputs": ["timeline event rows"],
        "called_by": ["scripts/run_stage_8_event_timeline.py"],
        "why": "Creates the first readable rally timeline while preserving uncertainty.",
    },
    {
        "area": "Stage 8 - Event Timeline",
        "file": "src/tennis_vision/rally_segmentation.py",
        "function": "build_rally_segments",
        "purpose": "Builds conservative rally segments from trajectory anchors.",
        "inputs": ["trajectory rows", "timeline events", "FPS"],
        "outputs": ["rally segment rows"],
        "called_by": ["scripts/run_stage_8_event_timeline.py"],
        "why": "Provides a first segment boundary without inferring score or outcome.",
    },
    {
        "area": "Stage 8.1 - Timeline Validation",
        "file": "src/tennis_vision/label_expansion.py",
        "function": "load_durable_or_fallback_labels",
        "purpose": "Loads durable expanded labels first, then latest session backup, then Stage 4.1 fallback labels.",
        "inputs": ["expanded labels path", "fallback labels path"],
        "outputs": ["labels", "source metadata", "warnings"],
        "called_by": ["scripts/run_stage_8_1_expand_labels.py"],
        "why": "Prevents non-interactive validation from downgrading manual label coverage.",
    },
    {
        "area": "Stage 8.1 - Timeline Validation",
        "file": "src/tennis_vision/label_expansion.py",
        "function": "write_label_session_backup",
        "purpose": "Writes timestamped CSV and JSON backups for labels collected in an interactive session.",
        "inputs": ["session directory", "timestamp", "labels"],
        "outputs": ["backup CSV path", "backup JSON path"],
        "called_by": ["scripts/run_stage_8_1_expand_labels.py"],
        "why": "Protects manual labeling work from later validation runs or report regeneration.",
    },
    {
        "area": "Stage 8.1 - Timeline Validation",
        "file": "src/tennis_vision/label_expansion.py",
        "function": "latest_label_session_csv",
        "purpose": "Finds the newest timestamped Stage 8.1 label session backup.",
        "inputs": ["label session directory"],
        "outputs": ["latest session CSV path or None"],
        "called_by": ["load_durable_or_fallback_labels"],
        "why": "Allows non-interactive validation to recover from a missing or incomplete durable expanded label file.",
    },
    {
        "area": "Stage 8.1 - Timeline Validation",
        "file": "src/tennis_vision/timeline_validation.py",
        "function": "validate_timeline_events",
        "purpose": "Checks whether timeline events are supported by nearby expanded ball labels.",
        "inputs": ["timeline rows", "expanded labels"],
        "outputs": ["validation rows, validated timeline, summary"],
        "called_by": ["scripts/run_stage_8_1_expand_labels.py"],
        "why": "This is the gate before tactical metrics.",
    },
    {
        "area": "Stage 8.2 - Manual Event Labeling",
        "file": "src/tennis_vision/event_labeling.py",
        "function": "collect_event_labels_interactively",
        "purpose": "Lets the user label bounce, hit, no_event, uncertain, or skipped frames.",
        "inputs": ["video path", "selected frames", "ball labels", "automatic events", "OpenCV UI settings"],
        "outputs": ["new manual event labels", "frames shown", "warnings", "errors"],
        "called_by": ["scripts/run_stage_8_2_event_labeling_helper.py"],
        "why": "This creates ground truth for event validation and prevents side-view replay from guessing event semantics.",
    },
    {
        "area": "Stage 8.2 - Manual Event Labeling",
        "file": "src/tennis_vision/event_labeling.py",
        "function": "compare_manual_events_to_auto_events",
        "purpose": "Compares manual event labels against automatic event hypotheses.",
        "inputs": ["manual event labels", "automatic events", "candidate window"],
        "outputs": ["comparison rows", "match summary"],
        "called_by": ["scripts/run_stage_8_2_event_labeling_helper.py"],
        "why": "This reveals whether the model is confusing hits, bounces, and uncertain interactions.",
    },
    {
        "area": "Stage 8.2 - Manual Event Labeling",
        "file": "src/tennis_vision/event_labeling.py",
        "function": "load_durable_event_labels",
        "purpose": "Loads persisted manual event labels or the latest timestamped session backup.",
        "inputs": ["manual event labels path"],
        "outputs": ["labels", "source metadata", "warnings"],
        "called_by": ["scripts/run_stage_8_2_event_labeling_helper.py"],
        "why": "Manual event labels should persist and become the default validation source.",
    },
    {
        "area": "Stage 8.2 - Manual Event Labeling",
        "file": "src/tennis_vision/event_labeling.py",
        "function": "write_event_label_session_backup",
        "purpose": "Writes timestamped backups for labels collected in an interactive session.",
        "inputs": ["session directory", "timestamp", "labels"],
        "outputs": ["backup CSV and JSON paths"],
        "called_by": ["scripts/run_stage_8_2_event_labeling_helper.py"],
        "why": "Protects manual event labeling work from accidental overwrite.",
    },
    {
        "area": "Stage 8.3 - Event Validation",
        "file": "src/tennis_vision/event_validation.py",
        "function": "group_manual_event_windows",
        "purpose": "Groups adjacent manual bounce labels into one bounce window.",
        "inputs": ["manual event labels", "bounce window gap"],
        "outputs": ["manual event window rows"],
        "called_by": ["scripts/run_stage_8_3_event_validation.py"],
        "why": "A real bounce can span several video frames, so nearby bounce labels should not become separate bounces.",
    },
    {
        "area": "Stage 8.3 - Event Validation",
        "file": "src/tennis_vision/event_validation.py",
        "function": "classify_validation_status",
        "purpose": "Compares one automatic event with nearby manual labels or windows.",
        "inputs": ["automatic event", "manual evidence", "manual hit count", "frame range", "validation window"],
        "outputs": ["validation status", "reason"],
        "called_by": ["build_validation_results"],
        "why": "This makes the automatic event decision explainable before reclassification.",
    },
    {
        "area": "Stage 8.3 - Event Validation",
        "file": "src/tennis_vision/event_reclassification.py",
        "function": "reclassify_auto_event",
        "purpose": "Reclassifies automatic hit/bounce hypotheses using manual event labels.",
        "inputs": ["automatic event", "validation status", "nearest manual label", "manual hit count"],
        "outputs": ["validated event type", "render role", "confidence adjustment", "reason"],
        "called_by": ["scripts/run_stage_8_3_event_validation.py"],
        "why": "This prevents the renderer from showing implausible hits when manual labels indicate bounce or no-event.",
    },
    {
        "area": "Stage 8.4 - Bounce Candidate Propagation",
        "file": "src/tennis_vision/bounce_candidate_propagation.py",
        "function": "build_manual_hit_windows",
        "purpose": "Groups manual hit labels into conservative exclusion windows.",
        "inputs": ["manual event label rows", "hit window gap", "padding"],
        "outputs": ["manual hit windows"],
        "called_by": ["scripts/run_stage_8_4_bounce_candidate_propagation.py"],
        "why": "Prevents the system from proposing a manually reviewed hit region as a bounce.",
    },
    {
        "area": "Stage 8.4 - Bounce Candidate Propagation",
        "file": "src/tennis_vision/bounce_candidate_propagation.py",
        "function": "learn_bounce_window_signature",
        "purpose": "Extracts a local motion signature from manually labeled bounce windows.",
        "inputs": ["motion feature rows", "manual bounce windows"],
        "outputs": ["weak bounce signature dictionary"],
        "called_by": ["scripts/run_stage_8_4_bounce_candidate_propagation.py"],
        "why": "This is the first step toward using one manual bounce label to find other bounce candidates automatically.",
    },
    {
        "area": "Stage 8.4 - Bounce Candidate Propagation",
        "file": "src/tennis_vision/bounce_candidate_propagation.py",
        "function": "apply_event_sequence_constraints",
        "purpose": "Applies hit, no_event, uncertain, and post-hit sequence rules to candidate bounce frames.",
        "inputs": ["candidate rows", "bounce windows", "hit windows", "no_event zones", "uncertain labels", "features"],
        "outputs": ["accepted candidate rows", "constraint summary"],
        "called_by": ["propose_bounce_candidates"],
        "why": "Keeps candidate propagation aligned with tennis event order instead of only local visual similarity.",
    },
    {
        "area": "Stage 8.4 - Bounce Candidate Propagation",
        "file": "src/tennis_vision/bounce_candidate_propagation.py",
        "function": "search_next_bounce_after_hit",
        "purpose": "Finds a manual hit after the known bounce and starts next-bounce search after that hit window.",
        "inputs": ["manual bounce windows", "manual hit windows", "feature rows"],
        "outputs": ["post-hit search context"],
        "called_by": ["apply_event_sequence_constraints"],
        "why": "The next bounce should be searched after the player hit, not at the hit frame.",
    },
    {
        "area": "Stage 8.4 - Bounce Candidate Propagation",
        "file": "src/tennis_vision/bounce_candidate_propagation.py",
        "function": "propose_bounce_candidates",
        "purpose": "Scores the rest of the trajectory for likely bounce candidates after event-sequence constraints.",
        "inputs": ["motion feature rows", "manual bounce windows", "manual hit windows", "no_event zones", "uncertain labels", "score threshold", "candidate window gap", "max candidates"],
        "outputs": ["candidate windows", "candidate frame rows", "constraint summary"],
        "called_by": ["scripts/run_stage_8_4_bounce_candidate_propagation.py"],
        "why": "Reduces manual labeling burden by suggesting events for review.",
    },
    {
        "area": "Stage 8.4 - Bounce Candidate Propagation",
        "file": "src/tennis_vision/bounce_pattern_features.py",
        "function": "compute_local_motion_features",
        "purpose": "Computes proxy movement features for projected ball points.",
        "inputs": ["ball sequence rows"],
        "outputs": ["feature rows with delta, speed, acceleration proxy, and direction-change signals"],
        "called_by": ["scripts/run_stage_8_4_bounce_candidate_propagation.py"],
        "why": "Bounce propagation needs local motion evidence without claiming physical truth.",
    },
    {
        "area": "Stage 8.3 - Event Validation",
        "file": "src/tennis_vision/event_reclassification.py",
        "function": "build_validated_event_timeline",
        "purpose": "Builds the downstream validated event timeline from validation results.",
        "inputs": ["event validation result rows"],
        "outputs": ["validated event timeline rows"],
        "called_by": ["scripts/run_stage_8_3_event_validation.py"],
        "why": "Stage 14.3 can consume this instead of raw possible_hit hypotheses.",
    },
    {
        "area": "Stage 9 - Tactical Metrics",
        "file": "src/tennis_vision/court_zones.py",
        "function": "assign_court_zone",
        "purpose": "Assigns a normalized ball point to an approximate tactical court zone.",
        "inputs": ["projected_x", "projected_y"],
        "outputs": ["zone id", "depth", "lateral lane", "side", "confidence-like score"],
        "called_by": ["build_ball_zone_assignments"],
        "why": "This turns raw tracking coordinates into tennis-readable shot placement information.",
    },
    {
        "area": "Stage 9 - Tactical Metrics",
        "file": "src/tennis_vision/court_zones.py",
        "function": "classify_depth",
        "purpose": "Classifies a normalized court y coordinate as short, mid, deep, or unknown.",
        "inputs": ["projected_y"],
        "outputs": ["depth class"],
        "called_by": ["assign_court_zone"],
        "why": "Depth is one of the most important first tactical summaries.",
    },
    {
        "area": "Stage 9 - Tactical Metrics",
        "file": "src/tennis_vision/tactical_metrics.py",
        "function": "build_ball_zone_assignments",
        "purpose": "Combines manual labels, trajectory rows, and projected candidates into zone assignment rows.",
        "inputs": ["expanded labels", "smoothed trajectory", "projected candidate rows"],
        "outputs": ["ball zone assignment rows"],
        "called_by": ["scripts/run_stage_9_tactical_metrics.py"],
        "why": "This is the main bridge from validated ball data to tactical placement outputs.",
    },
    {
        "area": "Stage 9 - Tactical Metrics",
        "file": "src/tennis_vision/tactical_metrics.py",
        "function": "estimate_shot_directions",
        "purpose": "Estimates approximate crosscourt/down-the-line/center-like movement between consecutive ball points.",
        "inputs": ["zone assignment rows"],
        "outputs": ["shot direction estimate rows"],
        "called_by": ["scripts/run_stage_9_tactical_metrics.py"],
        "why": "Direction estimates are a first tactical signal, but they remain hypothesis-based.",
    },
    {
        "area": "Stage 9 - Tactical Metrics",
        "file": "src/tennis_vision/tactical_metrics.py",
        "function": "build_rally_tactical_summary",
        "purpose": "Summarizes dominant zone/depth/lane for each rally segment.",
        "inputs": ["rally segment rows", "zone assignment rows"],
        "outputs": ["rally tactical summary rows"],
        "called_by": ["scripts/run_stage_9_tactical_metrics.py"],
        "why": "This gives the Product Owner a compact rally-level tactical readout.",
    },
    {
        "area": "Stage 9.1 - Projection Coverage",
        "file": "src/tennis_vision/projection_coverage.py",
        "function": "load_stage_3_homography",
        "purpose": "Loads the Stage 3 image-to-court homography from the calibration report.",
        "inputs": ["Stage 3 calibration report path"],
        "outputs": ["homography matrix", "metadata", "errors"],
        "called_by": ["scripts/run_stage_9_1_projection_coverage.py"],
        "why": "Projection coverage depends on the same validated court calibration used by earlier stages.",
    },
    {
        "area": "Stage 9.1 - Projection Coverage",
        "file": "src/tennis_vision/projection_coverage.py",
        "function": "project_labels_to_court",
        "purpose": "Projects expanded manual ball labels from image pixels into normalized court space.",
        "inputs": ["expanded label rows", "homography matrix"],
        "outputs": ["projected label rows with projection status"],
        "called_by": ["scripts/run_stage_9_1_projection_coverage.py"],
        "why": "This reduces unknown tactical zones by giving all validated labels court coordinates when possible.",
        "notes": "Out-of-range projections are preserved as uncertainty instead of forced into confident zones.",
    },
    {
        "area": "Stage 9.1 - Projection Coverage",
        "file": "src/tennis_vision/projection_coverage.py",
        "function": "calculate_projection_coverage",
        "purpose": "Compares Stage 9 projection coverage with Stage 9.1 projected label coverage.",
        "inputs": ["projected Stage 9.1 labels", "Stage 9 zone rows"],
        "outputs": ["before/after projection coverage metrics"],
        "called_by": ["scripts/run_stage_9_1_projection_coverage.py"],
        "why": "Shows whether the unknown-zone problem actually improved.",
    },
    {
        "area": "Stage 9.1 - Projection Coverage",
        "file": "src/tennis_vision/court_zone_tuning.py",
        "function": "assign_tuned_court_zone",
        "purpose": "Assigns a tuned approximate zone while preserving missing and out-of-bounds uncertainty.",
        "inputs": ["projected_x", "projected_y", "optional tuning config"],
        "outputs": ["tuned zone", "depth", "lane", "confidence-like score", "notes"],
        "called_by": ["tune_zone_assignments"],
        "why": "This turns improved projection coverage into more readable tactical placement without pretending to be official line calling.",
    },
    {
        "area": "Stage 9.1 - Projection Coverage",
        "file": "src/tennis_vision/court_zone_tuning.py",
        "function": "tune_zone_assignments",
        "purpose": "Applies tuned zone assignment to every projected expanded label.",
        "inputs": ["merged projected labels and Stage 9 assignment context"],
        "outputs": ["tuned ball zone assignment rows"],
        "called_by": ["scripts/run_stage_9_1_projection_coverage.py"],
        "why": "This creates the Stage 9.1 replacement zone assignment artifact.",
    },
    {
        "area": "Stage 9.1 - Projection Coverage",
        "file": "src/tennis_vision/court_zone_tuning.py",
        "function": "compare_stage_9_to_9_1",
        "purpose": "Builds frame-level before/after comparison rows for Stage 9 and Stage 9.1.",
        "inputs": ["Stage 9 zone rows", "Stage 9.1 tuned rows"],
        "outputs": ["comparison rows with improvement status"],
        "called_by": ["scripts/run_stage_9_1_projection_coverage.py"],
        "why": "The Product Owner can see which frames improved from unknown or gained projection.",
    },
    {
        "area": "Stage 10 - Analytical Report",
        "file": "src/tennis_vision/analytical_report.py",
        "function": "read_stage_inputs",
        "purpose": "Loads Stage 10 input files from Stage 9.1, Stage 8.1, Stage 7.1, and Stage 6.",
        "inputs": ["input path map"],
        "outputs": ["loaded row collections", "warnings", "errors"],
        "called_by": ["scripts/run_stage_10_analytical_report.py"],
        "why": "This controls which upstream evidence is used in the final analytical report.",
    },
    {
        "area": "Stage 10 - Analytical Report",
        "file": "src/tennis_vision/analytical_report.py",
        "function": "build_analysis_summary",
        "purpose": "Builds one structured summary of placement, direction, player, event, and rally evidence.",
        "inputs": ["loaded Stage 10 data"],
        "outputs": ["summary dictionary"],
        "called_by": ["scripts/run_stage_10_analytical_report.py"],
        "why": "This is the data model behind the player-readable report.",
    },
    {
        "area": "Stage 10 - Analytical Report",
        "file": "src/tennis_vision/analytical_report.py",
        "function": "build_plain_language_report",
        "purpose": "Converts tactical metrics and validated timeline evidence into a readable report.",
        "inputs": ["summary", "key findings", "coaching observations", "confidence", "paths", "verdict"],
        "outputs": ["plain-text-friendly Markdown report content"],
        "called_by": ["scripts/run_stage_10_analytical_report.py"],
        "why": "This is the first stage where raw analysis becomes a player-readable explanation.",
        "notes": "The wording preserves possible_* uncertainty and avoids official coaching claims.",
    },
    {
        "area": "Stage 10 - Analytical Report",
        "file": "src/tennis_vision/coaching_summary.py",
        "function": "build_coaching_observations",
        "purpose": "Builds cautious rule-based coaching-style observations from the analytical summary.",
        "inputs": ["analysis summary", "confidence summary"],
        "outputs": ["observation dictionaries"],
        "called_by": ["scripts/run_stage_10_analytical_report.py"],
        "why": "This gives the Product Owner readable observations without external AI or overclaiming.",
    },
    {
        "area": "Stage 10 - Analytical Report",
        "file": "src/tennis_vision/coaching_summary.py",
        "function": "build_key_findings",
        "purpose": "Builds short report findings for the executive summary.",
        "inputs": ["analysis summary", "confidence summary"],
        "outputs": ["short finding strings"],
        "called_by": ["scripts/run_stage_10_analytical_report.py"],
        "why": "Key findings help a player or Product Owner scan the report quickly.",
    },
    {
        "area": "Stage 10 - Analytical Report",
        "file": "src/tennis_vision/report_confidence.py",
        "function": "evaluate_report_confidence",
        "purpose": "Scores confidence from labels, projection coverage, candidate distance, event support, and player identity context.",
        "inputs": ["evidence counts", "candidate validation rows"],
        "outputs": ["confidence level", "reasons", "limitations", "validation steps"],
        "called_by": ["scripts/run_stage_10_analytical_report.py"],
        "why": "This prevents the final report from sounding more certain than the evidence supports.",
    },
    {
        "area": "Stage 11 - Report Package",
        "file": "src/tennis_vision/report_package.py",
        "function": "build_report_package",
        "purpose": "Collects selected analysis outputs into a clean delivery package.",
        "inputs": ["package root", "artifact descriptors", "copy mode"],
        "outputs": ["updated artifact descriptors", "warnings"],
        "called_by": ["scripts/run_stage_11_report_package.py"],
        "why": "This creates the first shareable output bundle from the whole analysis pipeline.",
    },
    {
        "area": "Stage 11 - Report Package",
        "file": "src/tennis_vision/report_package.py",
        "function": "write_package_readme",
        "purpose": "Writes the package README with status, contents, limitations, and reading order.",
        "inputs": ["README path", "verdict", "confidence", "timestamp", "next step"],
        "outputs": ["package README"],
        "called_by": ["scripts/run_stage_11_report_package.py"],
        "why": "The README is the first file a Product Owner should open in the deliverable package.",
    },
    {
        "area": "Stage 11 - Report Package",
        "file": "src/tennis_vision/report_package.py",
        "function": "write_package_index",
        "purpose": "Writes a vertical-block index for every included or missing package artifact.",
        "inputs": ["index path", "artifact descriptors"],
        "outputs": ["package_index.md"],
        "called_by": ["scripts/run_stage_11_report_package.py"],
        "why": "This makes the package readable without guessing where files came from.",
    },
    {
        "area": "Stage 11 - Report Package",
        "file": "src/tennis_vision/package_manifest.py",
        "function": "build_manifest",
        "purpose": "Builds package_manifest.json with included and missing artifacts.",
        "inputs": ["package metadata", "artifact descriptors", "warnings", "errors"],
        "outputs": ["manifest dictionary"],
        "called_by": ["scripts/run_stage_11_report_package.py"],
        "why": "The manifest gives future UI/reporting code a structured package inventory.",
    },
    {
        "area": "Stage 11 - Report Package",
        "file": "src/tennis_vision/package_manifest.py",
        "function": "write_manifest",
        "purpose": "Writes the Stage 11 package manifest JSON.",
        "inputs": ["manifest path", "manifest dictionary"],
        "outputs": ["package_manifest.json"],
        "called_by": ["scripts/run_stage_11_report_package.py"],
        "why": "This is the machine-readable handoff file for the package.",
    },
    {
        "area": "Stage 12 - Replay Schema",
        "file": "src/tennis_vision/replay_data_builder.py",
        "function": "load_replay_inputs",
        "purpose": "Loads upstream court, trajectory, timeline, player, tactical, report, and package data for replay schema generation.",
        "inputs": ["source path dictionary"],
        "outputs": ["loaded replay source data", "warnings", "errors"],
        "called_by": ["scripts/run_stage_12_replay_schema.py"],
        "why": "This gathers the evidence that future replay renderers will consume.",
    },
    {
        "area": "Stage 12 - Replay Schema",
        "file": "src/tennis_vision/replay_data_builder.py",
        "function": "build_replay_schema",
        "purpose": "Builds the replay data contract from court, trajectory, player, timeline and tactical outputs.",
        "inputs": ["loaded replay data", "source paths", "timestamp", "schema version"],
        "outputs": ["replay schema dictionary"],
        "called_by": ["scripts/run_stage_12_replay_schema.py"],
        "why": "This is the bridge between analysis data and future synthetic replay videos.",
    },
    {
        "area": "Stage 12 - Replay Schema",
        "file": "src/tennis_vision/replay_data_builder.py",
        "function": "build_ball_trajectory",
        "purpose": "Builds raw, smoothed, and replay keyframe ball trajectory sections.",
        "inputs": ["Stage 6 trajectory rows", "Stage 9.1 tuned zone rows"],
        "outputs": ["raw_ball_points", "smoothed_ball_points", "replay_keyframes"],
        "called_by": ["build_replay_schema"],
        "why": "Replay renderers need ball keyframes before any synthetic playback can be built.",
    },
    {
        "area": "Stage 12 - Replay Schema",
        "file": "src/tennis_vision/replay_data_builder.py",
        "function": "build_event_timeline",
        "purpose": "Converts validated possible_* events into replay event records.",
        "inputs": ["Stage 8.1 validated timeline rows"],
        "outputs": ["event timeline list"],
        "called_by": ["build_replay_schema"],
        "why": "Future renderers need event markers while preserving uncertainty.",
    },
    {
        "area": "Stage 12 - Replay Schema",
        "file": "src/tennis_vision/replay_camera_presets.py",
        "function": "build_camera_profiles",
        "purpose": "Defines deterministic camera presets for future replay renderers.",
        "inputs": ["none"],
        "outputs": ["camera profile list"],
        "called_by": ["build_replay_schema", "scripts/run_stage_12_replay_schema.py"],
        "why": "Camera presets define future replay views without implying multi-angle video exists today.",
    },
    {
        "area": "Stage 12 - Replay Schema",
        "file": "src/tennis_vision/replay_schema.py",
        "function": "build_visual_layers",
        "purpose": "Defines renderer layer contracts for court, players, ball, trajectory, events, zones, timeline, and confidence overlays.",
        "inputs": ["none"],
        "outputs": ["visual layer list"],
        "called_by": ["build_replay_schema"],
        "why": "Renderer layers make uncertainty and required data explicit before video generation work begins.",
    },
    {
        "area": "Stage 12 - Replay Schema",
        "file": "src/tennis_vision/replay_schema.py",
        "function": "build_renderer_hints",
        "purpose": "Defines deterministic renderer policy, initial renderer recommendation, and uncertainty display rules.",
        "inputs": ["none"],
        "outputs": ["renderer hints dictionary"],
        "called_by": ["build_replay_schema"],
        "why": "This keeps future replay work local, deterministic, and honest about uncertainty.",
    },
    {
        "area": "Stage 12 - Replay Schema",
        "file": "src/tennis_vision/replay_data_builder.py",
        "function": "build_pretty_markdown",
        "purpose": "Writes a plain-text-friendly summary of the replay schema.",
        "inputs": ["schema", "verdict", "friction", "next step"],
        "outputs": ["Markdown text"],
        "called_by": ["scripts/run_stage_12_replay_schema.py"],
        "why": "The Product Owner can inspect what replay-ready data exists without opening JSON.",
    },
    {
        "area": "Stage 13 - 2D Tactical Replay",
        "file": "src/tennis_vision/replay_renderer_2d.py",
        "function": "load_replay_schema",
        "purpose": "Loads the Stage 12 replay schema for rendering.",
        "inputs": ["replay schema path"],
        "outputs": ["schema dictionary", "warnings", "errors"],
        "called_by": ["scripts/run_stage_13_2d_tactical_replay.py"],
        "why": "This ensures the renderer consumes the schema contract instead of inventing data.",
    },
    {
        "area": "Stage 13 - 2D Tactical Replay",
        "file": "src/tennis_vision/replay_renderer_2d.py",
        "function": "create_court_canvas",
        "purpose": "Creates the base image canvas and normalized court coordinate transform.",
        "inputs": ["court model"],
        "outputs": ["OpenCV image canvas", "court-to-canvas transform"],
        "called_by": ["render_replay_frame"],
        "why": "This converts court-space analysis data into visible replay coordinates.",
    },
    {
        "area": "Stage 13 - 2D Tactical Replay",
        "file": "src/tennis_vision/replay_renderer_2d.py",
        "function": "render_replay_frame",
        "purpose": "Renders one deterministic 2D tactical replay frame from court, ball, player and event data.",
        "inputs": ["schema", "display points", "current frame index", "players", "events"],
        "outputs": ["rendered OpenCV image"],
        "called_by": ["render_replay_frames"],
        "why": "This is the first step where analysis data becomes a generated visual replay.",
    },
    {
        "area": "Stage 13 - 2D Tactical Replay",
        "file": "src/tennis_vision/replay_renderer_2d.py",
        "function": "render_replay_frames",
        "purpose": "Renders all replay frames to the Stage 13 frames folder.",
        "inputs": ["schema", "output directory", "interpolation settings"],
        "outputs": ["frame paths", "render context", "warnings", "errors"],
        "called_by": ["scripts/run_stage_13_2d_tactical_replay.py"],
        "why": "Frame rendering is the primary success condition even if MP4 export is unavailable.",
    },
    {
        "area": "Stage 13 - 2D Tactical Replay",
        "file": "src/tennis_vision/replay_renderer_2d.py",
        "function": "export_replay_video",
        "purpose": "Attempts MP4 export from rendered frames using OpenCV VideoWriter.",
        "inputs": ["frame paths", "output video path", "fps"],
        "outputs": ["video generated flag", "warnings", "errors"],
        "called_by": ["scripts/run_stage_13_2d_tactical_replay.py"],
        "why": "Video export is useful but codec-dependent, so it is separated from core frame rendering.",
    },
    {
        "area": "Stage 13 - 2D Tactical Replay",
        "file": "src/tennis_vision/replay_renderer_2d.py",
        "function": "build_display_points",
        "purpose": "Creates measured and visual-only interpolated replay display points.",
        "inputs": ["replay keyframes", "interpolation settings"],
        "outputs": ["display point list"],
        "called_by": ["render_replay_frames"],
        "why": "It makes smoother animation possible while marking interpolated points as visual only.",
    },
    {
        "area": "Stage 14 - Side-View Replay",
        "file": "src/tennis_vision/ball_flight_estimator.py",
        "function": "estimate_synthetic_height",
        "purpose": "Creates a synthetic height profile for side-view replay when measured 3D height is unavailable.",
        "inputs": ["sequence index", "total points", "nearby event type"],
        "outputs": ["synthetic height value"],
        "called_by": ["build_side_view_keyframes"],
        "why": "This enables side-view analytical video without pretending the system measured real ball height.",
    },
    {
        "area": "Stage 14 - Side-View Replay",
        "file": "src/tennis_vision/ball_flight_estimator.py",
        "function": "build_side_view_keyframes",
        "purpose": "Builds side-view keyframes with court depth and synthetic height annotations.",
        "inputs": ["replay schema"],
        "outputs": ["side-view keyframe rows"],
        "called_by": ["scripts/run_stage_14_side_view_replay.py", "render_side_view_frames"],
        "why": "This converts the replay schema into the side-view renderer's data model.",
    },
    {
        "area": "Stage 14 - Side-View Replay",
        "file": "src/tennis_vision/ball_flight_estimator.py",
        "function": "interpolate_side_view_motion",
        "purpose": "Creates visual-only interpolation points between side-view keyframes.",
        "inputs": ["side-view keyframes", "interpolation settings"],
        "outputs": ["side-view display points"],
        "called_by": ["render_side_view_frames"],
        "why": "It smooths the animation while keeping interpolated positions distinct from measured keyframes.",
    },
    {
        "area": "Stage 14 - Side-View Replay",
        "file": "src/tennis_vision/replay_renderer_side_view.py",
        "function": "render_side_view_frame",
        "purpose": "Renders one side-view ball flight frame with court depth, net, synthetic arc, players, events, and timeline.",
        "inputs": ["schema", "display points", "current index", "players", "events"],
        "outputs": ["rendered OpenCV image"],
        "called_by": ["render_side_view_frames"],
        "why": "This creates the first side-view replay visualization from analysis data.",
    },
    {
        "area": "Stage 14 - Side-View Replay",
        "file": "src/tennis_vision/replay_renderer_side_view.py",
        "function": "render_side_view_frames",
        "purpose": "Renders all side-view frames to the Stage 14 frames folder.",
        "inputs": ["schema", "output directory", "interpolation settings"],
        "outputs": ["frame paths", "render context", "warnings", "errors"],
        "called_by": ["scripts/run_stage_14_side_view_replay.py"],
        "why": "Frame rendering is the primary success condition for the side-view replay.",
    },
    {
        "area": "Stage 14 - Side-View Replay",
        "file": "src/tennis_vision/replay_renderer_side_view.py",
        "function": "export_side_view_video",
        "purpose": "Attempts MP4 export from side-view frames using OpenCV VideoWriter.",
        "inputs": ["frame paths", "output video path", "fps"],
        "outputs": ["video generated flag", "warnings", "errors"],
        "called_by": ["scripts/run_stage_14_side_view_replay.py"],
        "why": "Video export is useful but codec-dependent, so it is not required for renderer success.",
    },
    {
        "area": "Stage 14.1 - Side-View Patch",
        "file": "src/tennis_vision/ball_flight_estimator.py",
        "function": "classify_height_anchor_type",
        "purpose": "Classifies replay events into bounce, hit, interaction, arc, or interpolation height roles.",
        "inputs": ["event type"],
        "outputs": ["height anchor type"],
        "called_by": ["estimate_synthetic_height", "build_side_view_keyframes"],
        "why": "This lets the side-view renderer treat bounce and hit moments differently.",
    },
    {
        "area": "Stage 14.1 - Side-View Patch",
        "file": "src/tennis_vision/ball_flight_estimator.py",
        "function": "enforce_bounce_floor_contact",
        "purpose": "Forces bounce-like events to visually ground near court surface in side-view replay.",
        "inputs": ["synthetic height"],
        "outputs": ["floor-grounded synthetic height"],
        "called_by": ["estimate_synthetic_height", "estimate_semantic_height_profile"],
        "why": "This makes the replay visually interpretable as tennis instead of showing floating bounces.",
    },
    {
        "area": "Stage 14.1 - Side-View Patch",
        "file": "src/tennis_vision/ball_flight_estimator.py",
        "function": "enforce_hit_contact_band",
        "purpose": "Constrains hit-like events to a plausible synthetic contact-height band.",
        "inputs": ["synthetic height"],
        "outputs": ["contact-band synthetic height"],
        "called_by": ["estimate_synthetic_height", "estimate_semantic_height_profile"],
        "why": "Hit markers should look plausible without claiming real measured 3D height.",
    },
    {
        "area": "Stage 14.1 - Side-View Patch",
        "file": "src/tennis_vision/ball_flight_estimator.py",
        "function": "estimate_semantic_height_profile",
        "purpose": "Creates a semantically constrained synthetic height profile.",
        "inputs": ["side-view point records"],
        "outputs": ["synthetic height values"],
        "called_by": ["build_side_view_keyframes"],
        "why": "This keeps the side-view useful without pretending the system measured real 3D height.",
    },
    {
        "area": "Stage 14.1 - Side-View Patch",
        "file": "src/tennis_vision/ball_flight_estimator.py",
        "function": "annotate_interpolated_height_points",
        "purpose": "Marks interpolated side-view points as visual estimates.",
        "inputs": ["side-view display points"],
        "outputs": ["annotated display points"],
        "called_by": ["interpolate_side_view_motion"],
        "why": "Interpolated points must not be mistaken for measured or event-anchored truth.",
    },
    {
        "area": "Stage 14.1 - Side-View Patch",
        "file": "src/tennis_vision/replay_renderer_side_view.py",
        "function": "create_semantic_debug_image",
        "purpose": "Writes a diagnostic side-view image showing semantic anchors and labels.",
        "inputs": ["schema", "side-view keyframes", "display points", "events", "players", "output path"],
        "outputs": ["semantic debug image"],
        "called_by": ["scripts/run_stage_14_side_view_replay.py"],
        "why": "The Product Owner can inspect whether bounces are grounded and hits/interpolation are labeled clearly.",
    },
    {
        "area": "Stage 14.2 - Side-View Event Disambiguation",
        "file": "src/tennis_vision/ball_flight_estimator.py",
        "function": "estimate_player_contact_window",
        "purpose": "Estimates a conservative court-depth window where a player could plausibly contact the ball.",
        "inputs": ["player record", "event frame", "depth tolerance"],
        "outputs": ["player contact window dictionary"],
        "called_by": ["score_hit_plausibility"],
        "why": "Hit labels should be constrained by where the player actually is, not only by ball trajectory shape.",
    },
    {
        "area": "Stage 14.2 - Side-View Event Disambiguation",
        "file": "src/tennis_vision/ball_flight_estimator.py",
        "function": "is_hit_plausible_for_player",
        "purpose": "Tests whether a candidate hit is plausible relative to player position and court depth.",
        "inputs": ["event record", "players", "depth tolerance"],
        "outputs": ["boolean plausibility result"],
        "called_by": ["classify_event_semantic_role"],
        "why": "This prevents the renderer from labeling clearly implausible in-court positions as hits.",
    },
    {
        "area": "Stage 14.2 - Side-View Event Disambiguation",
        "file": "src/tennis_vision/ball_flight_estimator.py",
        "function": "score_hit_plausibility",
        "purpose": "Scores possible_hit events against attributed player depth.",
        "inputs": ["event record", "players", "depth tolerance"],
        "outputs": ["plausibility score and explanation"],
        "called_by": ["is_hit_plausible_for_player", "downgrade_implausible_hits"],
        "why": "The Product Owner can see why a hit label was accepted or downgraded.",
    },
    {
        "area": "Stage 14.2 - Side-View Event Disambiguation",
        "file": "src/tennis_vision/ball_flight_estimator.py",
        "function": "downgrade_implausible_hits",
        "purpose": "Assigns render roles and downgrades raw possible_hit events that fail player-aware plausibility.",
        "inputs": ["event records", "player records"],
        "outputs": ["enriched events", "render-role summary"],
        "called_by": ["build_side_view_keyframes", "render_side_view_frames", "scripts/run_stage_14_side_view_replay.py"],
        "why": "It preserves raw event evidence while avoiding misleading hit labels in the replay.",
    },
    {
        "area": "Stage 14.2 - Side-View Event Disambiguation",
        "file": "src/tennis_vision/replay_renderer_side_view.py",
        "function": "assign_event_render_role",
        "purpose": "Separates raw event labels from final side-view render roles.",
        "inputs": ["event record"],
        "outputs": ["render role"],
        "called_by": ["render_event_markers", "render_timeline_strip"],
        "why": "This makes the side-view easier to read and prevents ambiguous tennis interpretation.",
    },
    {
        "area": "Stage 14.3 - Validated Events Side-View",
        "file": "src/tennis_vision/validated_event_source.py",
        "function": "load_validated_event_source",
        "purpose": "Loads Stage 8.3 validated events as the preferred source for side-view rendering.",
        "inputs": ["project root", "replay schema", "optional preferred Stage 8.3 path"],
        "outputs": ["normalized events", "source metadata", "warnings", "errors", "render summary"],
        "called_by": ["scripts/run_stage_14_side_view_replay.py"],
        "why": "Prevents raw automatic possible hits from being rendered as physical events.",
    },
    {
        "area": "Stage 14.3 - Validated Events Side-View",
        "file": "src/tennis_vision/validated_event_source.py",
        "function": "map_validated_event_to_render_role",
        "purpose": "Converts validated and reclassified event labels into physical or annotation render roles.",
        "inputs": ["event row", "source name", "replay schema"],
        "outputs": ["normalized event record with render policy"],
        "called_by": ["load_validated_event_source"],
        "why": "Separates real visual contact markers from uncertain model guesses.",
    },
    {
        "area": "Stage 14.3 - Validated Events Side-View",
        "file": "src/tennis_vision/validated_event_source.py",
        "function": "summarize_validated_render_events",
        "purpose": "Counts validated bounces, validated hits, downgraded hit annotations, rejected events, and unvalidated annotations.",
        "inputs": ["normalized event records"],
        "outputs": ["render count summary"],
        "called_by": ["scripts/run_stage_14_side_view_replay.py"],
        "why": "The Product Owner can confirm that no unvalidated hit is being rendered as a physical contact.",
    },
    {
        "area": "Stage 14.3 - Validated Events Side-View",
        "file": "src/tennis_vision/replay_renderer_side_view.py",
        "function": "create_validated_events_debug_image",
        "purpose": "Creates a debug image showing the main ball path, validated event source, and annotation policy.",
        "inputs": ["schema", "display points", "events", "players", "output path", "event source"],
        "outputs": ["validated-event debug image"],
        "called_by": ["scripts/run_stage_14_side_view_replay.py"],
        "why": "This lets the Product Owner verify that validated bounces are grounded and unvalidated hits are annotations only.",
    },
    {
        "area": "Lab Notebook",
        "file": "src/tennis_vision/lab_notebook.py",
        "function": "update_lab_notebook",
        "purpose": "Updates stage lab notebook pages and experiment index from reports.",
        "inputs": ["project root"],
        "outputs": ["lab notebook Markdown pages"],
        "called_by": ["stage scripts", "scripts/update_lab_notebook.py"],
        "why": "Keeps execution evidence current without manual documentation commands.",
    },
]


AREA_ORDER = [
    "Stage 0 - Environment",
    "Reports",
    "Friction",
    "Stage 1 - Video IO",
    "Stage 2 - YOLO CPU",
    "Stage 3 - Court Calibration",
    "Stage 3.1 - Court Point Selection",
    "Stage 4 - Ball Candidate Probe",
    "Stage 4.1 - Manual Ball Labeling",
    "Stage 5 - Candidate Filtering and Court Projection",
    "Stage 5.1 - Candidate Generation Improvement",
    "Stage 6 - Trajectory Smoothing",
    "Stage 7 - Player Interaction",
    "Stage 7.1 - Player Filtering and Identity",
    "Stage 8 - Event Timeline",
    "Stage 8.1 - Timeline Validation",
    "Stage 8.2 - Manual Event Labeling",
    "Stage 8.3 - Event Validation",
    "Stage 8.4 - Bounce Candidate Propagation",
    "Stage 9 - Tactical Metrics",
    "Stage 9.1 - Projection Coverage",
    "Stage 10 - Analytical Report",
    "Stage 11 - Report Package",
    "Stage 12 - Replay Schema",
    "Stage 13 - 2D Tactical Replay",
    "Stage 14 - Side-View Replay",
    "Stage 14.1 - Side-View Patch",
    "Stage 14.2 - Side-View Event Disambiguation",
    "Stage 14.3 - Validated Events Side-View",
    "Lab Notebook",
]


def find_line_numbers() -> dict[tuple[str, str], int]:
    """Find function/class line numbers using Python AST."""
    result: dict[tuple[str, str], int] = {}
    for path in sorted((PROJECT_ROOT / "src").rglob("*.py")) + sorted((PROJECT_ROOT / "scripts").glob("*.py")):
        relative = path.relative_to(PROJECT_ROOT).as_posix()
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                result[(relative, node.name)] = node.lineno
    return result


def bullet(items: list[str]) -> str:
    """Render a short bullet list for a vertical block."""
    return "\n".join(f"  - {item}" for item in items)


def render_entry(entry: dict[str, Any], line_numbers: dict[tuple[str, str], int]) -> str:
    """Render one function block."""
    file_path = entry["file"]
    function = entry["function"]
    line = line_numbers.get((file_path, function), "Not available")
    return "\n".join(
        [
            f"FUNCTION: {function}",
            f"FILE: {file_path}",
            f"LINE: {line}",
            f"AREA: {entry['area']}",
            "",
            "PURPOSE:",
            f"  {entry['purpose']}",
            "",
            "INPUTS:",
            bullet(entry.get("inputs", ["Not documented"])),
            "",
            "OUTPUTS:",
            bullet(entry.get("outputs", ["Not documented"])),
            "",
            "CALLED BY:",
            bullet(entry.get("called_by", ["Not documented"])),
            "",
            "WHY PRODUCT OWNER CARES:",
            f"  {entry.get('why', 'This function is part of the project flow.')}",
            "",
            "HOW TO FIND IT:",
            f"  Open {file_path} and go to line {line}.",
            f"  Search: def {function}",
            "",
            "NOTES:",
            f"  {entry.get('notes', 'None.')}",
            "",
            "---",
        ]
    )


def build_inventory() -> str:
    """Build the complete inventory document."""
    line_numbers = find_line_numbers()
    lines = [
        "# Function Inventory",
        "",
        "This document is designed to be readable as plain text.",
        "It avoids wide Markdown tables because the Product Owner often reviews documentation in TXT/editor view.",
        "",
        "Line numbers are generated from the current Python source with `scripts/update_function_inventory.py`.",
        "",
    ]
    for area in AREA_ORDER:
        entries = [entry for entry in FUNCTIONS if entry["area"] == area]
        if not entries:
            continue
        lines.extend([f"## {area}", ""])
        for entry in entries:
            lines.extend([render_entry(entry, line_numbers), ""])
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(build_inventory(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
